concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository
    != 'apereo/cas' }}
  group: workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{
    github.event.pull_request.id }}
env:
  GH_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GH_PACKAGE_REGISTRY_TOKEN }}
  GH_PACKAGE_REGISTRY_USER: ${{ secrets.GH_PACKAGE_REGISTRY_USER }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  GRADLE_OPTS: -Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server
  JAVA_OPTS: -Xms512m -Xmx6048m -Xss128m -XX:ReservedCodeCacheSize=512m -server
  JDK_CURRENT: 21
  JDK_DISTRIBUTION: corretto
  TERM: xterm-256color
jobs:
  initialize:
    needs:
    - trigger-ci
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.JDK_DISTRIBUTION }}
        java-version: ${{ env.JDK_CURRENT }}
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Initialize
      run: ls ./ci && find ./ci -type f -name "*.sh" -exec chmod +x "{}" \; && ./ci/init-build.sh
  static-analysis:
    continue-on-error: false
    name: ${{ matrix.category }}
    needs:
    - initialize
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.JDK_DISTRIBUTION }}
        java-version: ${{ env.JDK_CURRENT }}
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Initialize
      run: find ./ci -type f -name "*.sh" -exec chmod +x "{}" \; && ./ci/init-build.sh
    - continue-on-error: true
      name: Run Analysis
      run: ./gradlew --build-cache --no-watch-fs --configure-on-demand --parallel
        --no-daemon ${{ matrix.category }} -x test -x javadoc -DskipNestedConfigMetadataGen=true
        -Dverbose=true --max-workers=8
    strategy:
      matrix:
        category:
        - checkstyleMain
        - checkstyleTest
  trigger-ci:
    if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      || contains(github.event.pull_request.labels.*.name, 'CI')) && !contains(github.event.pull_request.labels.*.name,
      'Renovate') && !contains(github.event.head_commit.message, 'trigger dependency
      update') && !contains(github.event.head_commit.message, 'documentation update')
      }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Trigger CI
      run: echo "CI Triggered"
  validate-codebase:
    continue-on-error: false
    if: ${{ !contains(github.head_ref, 'renovate') }}
    name: ${{ matrix.check }}
    needs:
    - initialize
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.JDK_DISTRIBUTION }}
        java-version: ${{ env.JDK_CURRENT }}
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Initialize
      run: find ./ci -type f -name "*.sh" -exec chmod +x "{}" \; && ./ci/init-build.sh
    - continue-on-error: true
      name: Validate Codebase
      run: java ./ci/checks/${{ matrix.check }}.java .
    strategy:
      fail-fast: false
      matrix:
        check:
        - CheckAsyncAnnotationInInterface
        - CheckDuplicateGradleConfiguration
        - CheckFunctionalConditionUsage
        - CheckDuplicateTestConfiguration
        - CheckMissingUtilityClassAnnotation
        - CheckRedundantTestConfigurationInheritance
        - CheckSpringConfigurationBeanProxying
        - CheckSpringConfigurationFactories
        - CheckMissingTestTagAnnotation
        - CheckEnforceLombokAnnotations
        - CheckRequiredModuleAnnotationReferences
        - CheckMixingSpringBeanWithDependencyInjection
        - CheckMissingPuppeteerConfig
        - CheckSpringConfigurationConditionals
        - CheckMissingConditionalOnFeature
        - CheckPuppeteerScenarioScriptConfiguration
        - CheckMissingConditionalOnMissingBean
        - CheckNativeRuntimeHints
name: Code Analysis
on:
  repository_dispatch:
    types: trigger-ga___analysis.yml
