jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: stale
      uses: actions/stale@v9
      with:
        days-before-close: 0
        days-before-stale: 7
        exempt-draft-pr: true
        exempt-pr-labels: 'Pending: Work in Progress,WIP'
        stale-pr-message: This pull request has been open and inactive. It will be
          closed shortly.
    - continue-on-error: true
      name: Print outputs
      run: echo ${{ join(steps.stale.outputs.*, ',') }}
name: Stale Pull Requests
on:
  repository_dispatch:
    types: trigger-ga___stale-pullrequests.yml
permissions:
  issues: none
  pull-requests: write
